-- PASSO 1: execute no SQL Editor do banco vdsuugrouxxcstooiafa
create table if not exists public.config_periodos (
  id           bigint generated by default as identity primary key,
  nome_periodo text not null,
  meses        jsonb not null,
  labels       jsonb,
  total_meses  integer,
  created_at   timestamp default now()
);
create table if not exists public.dados_processos (
  id         bigint generated by default as identity primary key,
  periodo_id bigint not null references public.config_periodos(id) on delete cascade,
  aba        text not null,
  tipo       text not null,
  valores    jsonb not null,
  created_at timestamp default now()
);
create index if not exists idx_dados_processos_periodo on public.dados_processos(periodo_id);

-- Acesso equivalente ao banco antigo (a senha do app é validada no navegador)
alter table public.config_periodos enable row level security;
alter table public.dados_processos enable row level security;
drop policy if exists "anon_select" on public.config_periodos;
drop policy if exists "anon_insert" on public.config_periodos;
drop policy if exists "anon_select" on public.dados_processos;
drop policy if exists "anon_insert" on public.dados_processos;
create policy "anon_select" on public.config_periodos for select to anon using (true);
create policy "anon_insert" on public.config_periodos for insert to anon with check (true);
create policy "anon_select" on public.dados_processos for select to anon using (true);
create policy "anon_insert" on public.dados_processos for insert to anon with check (true);
